"use client";

import { useMemo, useState } from "react";

type Answers = { name:string; animals:string[]; petCount:string; social:string; energy:string; triggers:string; medical:string; medicalNotes:string; habitat:string; habitatNotes:string; handling:string };
const initial:Answers={name:"",animals:["Dog"],petCount:"1",social:"Loves people and seeks attention immediately.",energy:"Moderate Energy: Enjoys playtime but settles down easily.",triggers:"Easygoing: Calm and rarely stressed by changes.",medical:"No, my pet is completely healthy and needs standard care.",medicalNotes:"",habitat:"No / Not Applicable",habitatNotes:"",handling:"Friendly, calm, and easy to handle."};
const socialOptions=[["Loves people and seeks attention immediately.","♡"],["Shy: Needs time to warm up to strangers.","◌"],["Fearful: Hides or actively avoids new people.","⌂"],["Reactive: May snap, scratch, or growl if cornered.","⚑"]];
const energyOptions=[["Needs constant stimulation and intense exercise.","↟"],["Moderate Energy: Enjoys playtime but settles down easily.","↗"],["Low Energy: Prefers sleeping and short, gentle walks.","〰"],["Senior / Limited: Low stamina or has mobility issues.","⌁"]];
const triggerOptions=[["Easygoing: Calm and rarely stressed by changes.","○"],["Anxious: Panics when left alone (Separation Anxiety).","◇"],["Noise Sensitive: Scared of thunder, fireworks, or loud sounds.","⚡"],["Protective: Guards food, toys, or spaces from others.","◆"]];
const medicalOptions=[["No, my pet is completely healthy and needs standard care.","🟢"],["Yes, basic medication (Oral pills, liquid syrups, or topical ear/eye drops).","🟡"],["Yes, advanced/clinical care (Insulin injections, Sub-Q fluids, glucose monitoring, bandage changes, or post-op recovery).","🔴"]];
const handlingOptions=[["Friendly, calm, and easy to handle.","🟢"],["Anxious, shy, or easily stressed (Needs a slow introduction).","🟡"],["Reactive, aggressive, or difficult to medicate (Requires experienced veterinary handling).","🔴"]];
const steps=[["Pet profile","What type of pet(s) need care?","Check all that apply."],["Their social style","How would you describe them?","Choose the closest match for the pet who needs the most support."],["Daily rhythm","What are their energy levels like?","This helps shape playtime, walks, and rest."],["Stress & comfort","Do they have any triggers?","Knowing these early helps every visit feel safer."],["Medical & special needs","Does your pet require any medication or medical procedures?","Tell Melissanthi what level of support is needed."],["Routine & behavioral habits","For exotic pets: Are there specific habitat requirements to monitor?","For example: humidity controls, heat lamp regulation, or live feeding."],["Handling","How does your pet react to strangers or being handled?","This helps plan a calm, safe first introduction."]] as const;
const characterByAnimal:Record<string,{src?:string;emoji:string}>={
  "Dog":{src:"/pixel-characters/friendly-dog.svg",emoji:"🐶"},
  "Cat":{src:"/pixel-characters/royal-cat.svg",emoji:"🐱"},
  "Small Mammal / Rodent":{emoji:"🐰"},
  "Reptile / Amphibian":{src:"/pixel-characters/chaos-snake.svg",emoji:"🐍"},
  "Bird":{src:"/pixel-characters/calm-owl.svg",emoji:"🦜"},
  "Fish":{emoji:"🐠"}
};

function OptionList({options,value,onChange}:{options:string[][];value:string;onChange:(value:string)=>void}){return <div className="care-options">{options.map(([label,icon])=><button type="button" key={label} className={value===label?"selected":""} onClick={()=>onChange(label)}><span>{icon}</span><strong>{label}</strong><i>{value===label?"✓":""}</i></button>)}</div>}

export default function CarePlan(){
  const[screen,setScreen]=useState<"intro"|"quiz"|"loading"|"result">("intro");const[step,setStep]=useState(0);const[answers,setAnswers]=useState<Answers>(initial);const[petPhoto,setPetPhoto]=useState("");const[photoName,setPhotoName]=useState("");
  const pet=answers.name.trim()||(Number(answers.petCount)>1?"Your pets":"Your pet");const current=steps[step];const total=steps.length;const progress=((step+1)/total)*100;
  const persona=useMemo(()=>{if(answers.energy.startsWith("Senior"))return"The Wise Gentle Soul";if(answers.triggers.startsWith("Protective"))return"The Loyal Guardian";if(answers.social.startsWith("Reactive"))return"The Brave Boundary Keeper";if(answers.social.startsWith("Fearful"))return"The Gentle Homebody";if(answers.social.startsWith("Shy"))return answers.energy.startsWith("Low")?"The Quiet Comfort Seeker":"The Soft-Hearted Explorer";if(answers.energy.startsWith("Needs constant"))return"The Joyful Adventure Spark";if(answers.triggers.startsWith("Anxious"))return"The Devoted Shadow";if(answers.triggers.startsWith("Noise Sensitive"))return"The Tender-Hearted Companion";return"The Warm-Hearted Playmate"},[answers.energy,answers.social,answers.triggers]);
  const character=characterByAnimal[answers.animals[0]]||characterByAnimal.Dog;
  function toggleAnimal(animal:string){setAnswers(a=>({...a,animals:a.animals.includes(animal)?a.animals.filter(x=>x!==animal):[...a.animals,animal]}))}
  function addPhoto(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file||!file.type.startsWith("image/"))return;const reader=new FileReader();reader.onload=()=>{setPetPhoto(String(reader.result||""));setPhotoName(file.name)};reader.readAsDataURL(file)}
  function next(){if(step<total-1)setStep(step+1);else{setScreen("loading");window.setTimeout(()=>setScreen("result"),900)}}
  function restart(){setAnswers(initial);setPetPhoto("");setPhotoName("");setStep(0);setScreen("intro")}
  const medicalSummary=answers.medical.startsWith("No,")?"Standard care":answers.medical.startsWith("Yes, basic")?"Basic medication":"Advanced clinical care";const animals=answers.animals.join(", ")||"Pet type not selected";
  const whatsapp=`https://wa.me/306980770839?text=${encodeURIComponent(`Hi Melissanthi! I completed the pet questionnaire for ${pet}. Pets: ${answers.petCount} (${animals}). Personality: ${answers.social} Energy: ${answers.energy} Triggers: ${answers.triggers} Medical support: ${answers.medical} ${answers.medicalNotes?`Notes: ${answers.medicalNotes}.`:""} Habitat: ${answers.habitat}${answers.habitatNotes?` — ${answers.habitatNotes}`:""}. Handling: ${answers.handling}`)}`;

  function questionBody(){
    if(step===0)return <><div className="care-options care-pet-types">{[["Dog","🐶"],["Cat","🐱"],["Small Mammal / Rodent","🐰"],["Reptile / Amphibian","🐍"],["Bird","🦜"],["Fish","🐠"]].map(([label,icon])=><button type="button" key={label} className={answers.animals.includes(label)?"selected":""} onClick={()=>toggleAnimal(label)}><span>{icon}</span><strong>{label}</strong><i>{answers.animals.includes(label)?"✓":""}</i></button>)}</div><label className="care-field">How many pets total?<select value={answers.petCount} onChange={e=>setAnswers({...answers,petCount:e.target.value})}>{Array.from({length:10},(_,i)=><option key={i+1}>{i+1}</option>)}</select></label></>;
    if(step===1)return <OptionList options={socialOptions} value={answers.social} onChange={social=>setAnswers({...answers,social})}/>;
    if(step===2)return <OptionList options={energyOptions} value={answers.energy} onChange={energy=>setAnswers({...answers,energy})}/>;
    if(step===3)return <OptionList options={triggerOptions} value={answers.triggers} onChange={triggers=>setAnswers({...answers,triggers})}/>;
    if(step===4)return <><OptionList options={medicalOptions} value={answers.medical} onChange={medical=>setAnswers({...answers,medical})}/><label className="care-field">Please describe any medical conditions or specific nursing care required:<textarea value={answers.medicalNotes} onChange={e=>setAnswers({...answers,medicalNotes:e.target.value})} placeholder="Add details here (optional)"/></label></>;
    if(step===5)return <><OptionList options={[["Yes","✓"],["No / Not Applicable","—"]]} value={answers.habitat} onChange={habitat=>setAnswers({...answers,habitat})}/>{answers.habitat==="Yes"&&<label className="care-field">Please describe the habitat requirements:<textarea value={answers.habitatNotes} onChange={e=>setAnswers({...answers,habitatNotes:e.target.value})} placeholder="Humidity, temperature, lighting, feeding…"/></label>}</>;
    return <OptionList options={handlingOptions} value={answers.handling} onChange={handling=>setAnswers({...answers,handling})}/>;
  }

  return <section className="care" id="care-plan">
    {screen==="intro"&&<div className="care-intro"><div><p className="care-label">A little help from Meli’s assistant</p><h2>Tell us what makes your pet <em>them.</em></h2><p>A friendly questionnaire covering personality, energy, triggers, medical needs, and handling.</p><label>Pet’s name <small>(optional)</small><input value={answers.name} onChange={e=>setAnswers({...answers,name:e.target.value})} placeholder="e.g. Luna"/></label><label className="care-photo-upload"><span>{petPhoto?"✓ Photo added":"Add your pet’s photo"} <small>(optional)</small></span><input type="file" accept="image/*" onChange={addPhoto}/>{petPhoto&&<em>{photoName}</em>}</label><button className="care-primary" onClick={()=>setScreen("quiz")}>Start questionnaire <span>→</span></button><small>No medical advice and no data saved.</small></div><div className="care-intro-art"><img src="/pixel-characters/affectionate-dog.svg" alt=""/><p>Every pet has<br/>their own rhythm.</p></div></div>}
    {screen==="quiz"&&<div className="care-quiz"><aside><button onClick={()=>step?setStep(step-1):setScreen("intro")}>← Back</button><div><p className="care-label">Pet questionnaire</p><h2>A better plan starts with the little things.</h2></div><b>{String(step+1).padStart(2,"0")} / {String(total).padStart(2,"0")}</b></aside><div className="care-question"><div className="care-progress"><i style={{width:`${progress}%`}}/></div><p className="care-label">{current[0]}</p><h3>{current[1]}</h3><p>{current[2]}</p>{questionBody()}<div className="care-actions"><small>Question {step+1} of {total}</small><button className="care-primary" onClick={next} disabled={step===0&&answers.animals.length===0}>{step===total-1?"See their character":"Continue"} <span>→</span></button></div></div></div>}
    {screen==="loading"&&<div className="care-loading"><span>✦</span><p className="care-label">Meli’s assistant is thinking</p><h2>Getting to know {pet}…</h2></div>}
    {screen==="result"&&<div className="care-result"><header><p className="care-label">Questionnaire complete</p><h2>Meet {pet}’s care character.</h2><p>Melissanthi will confirm every detail with you before care begins.</p></header><div className="care-result-grid care-result-simple"><article className="care-plan-card"><small>{answers.petCount} pet{answers.petCount==="1"?"":"s"} · {animals}</small><h3>A thoughtful introduction, shaped around them.</h3><p className="care-verdict">Their starting care profile calls for <strong>{medicalSummary.toLowerCase()}</strong> and an approach that respects their boundaries.</p><div className="care-times"><p><b>♡</b><span><strong>Personality</strong>{answers.social}</span></p><p><b>↗</b><span><strong>Energy</strong>{answers.energy}</span></p><p><b>◇</b><span><strong>Triggers</strong>{answers.triggers}</span></p><p><b>＋</b><span><strong>Handling & health</strong>{medicalSummary} · {answers.handling}</span></p></div></article><article className={`care-persona-card ${petPhoto?"has-pet-photo":""}`}>{petPhoto&&<img className="care-pet-photo" src={petPhoto} alt={`${pet} uploaded by their human`}/>} {character.src?<img className={petPhoto?"care-character-badge":"care-character-fallback"} src={character.src} alt={`${answers.animals[0]} character`}/>:<span className={petPhoto?"care-species-emoji care-species-emoji-badge":"care-species-emoji"} role="img" aria-label={`${answers.animals[0]} character`}>{character.emoji}</span>}<p className="care-label">{pet}’s care character</p><h3>{persona}</h3><p className="care-persona-verdict">A playful character description based on their social style, energy, and triggers.</p><div className="care-traits"><strong>🐇 {answers.social.split(":")[0]}</strong><strong>🐇 {answers.energy.split(":")[0]}</strong><strong>🐇 {answers.triggers.split(":")[0]}</strong>{answers.habitat==="Yes"&&<strong>🐇 Habitat support</strong>}</div></article></div><div className="care-cta"><div><small>Ready for the human part?</small><h3>Send the questionnaire to Melissanthi.</h3></div><div><a href={whatsapp} target="_blank" rel="noreferrer">Continue on WhatsApp ↗</a><button onClick={restart}>Start again</button></div></div></div>}
  </section>
}
