"use client";

import { useEffect, useMemo, useState } from "react";

type Answers = { name:string; animal:string; personality:string; needs:string[]; away:string; joy:string };
const initial:Answers={name:"",animal:"Dog",personality:"Affectionate but cautious",needs:[],away:"A long weekend",joy:"Slow walks & sniffing"};
const characters:Record<string,string>={
  "Affectionate but cautious":"/pixel-characters/affectionate-dog.svg",
  "Independent royalty":"/pixel-characters/royal-cat.svg",
  "Friendly with everyone":"/pixel-characters/friendly-dog.svg",
  "Shy until snacks appear":"/pixel-characters/shy-cat.svg",
  "Professional chaos goblin":"/pixel-characters/chaos-snake.svg",
  "Calm little observer":"/pixel-characters/calm-owl.svg"
};
const questions=[
  {key:"animal",eyebrow:"First things first",title:"Who are we caring for?",help:"Choose the closest match.",options:[["Dog","🐕"],["Cat","🐈"],["Rabbit","🐇"],["Bird","🦜"],["Reptile","🦎"],["Small animal","🐹"]]},
  {key:"personality",eyebrow:"Their social style",title:"How would you describe them?",help:"This helps shape the pace of the first visits.",options:[["Affectionate but cautious",""],["Independent royalty",""],["Friendly with everyone",""],["Shy until snacks appear",""],["Professional chaos goblin",""],["Calm little observer",""]]},
  {key:"needs",eyebrow:"Care details",title:"Any special needs?",help:"Select as many as needed.",options:[["Medication","＋"],["Senior care","⌁"],["Young & energetic","↟"],["Special feeding","◇"],["Mobility support","≈"],["None right now","✓"]]},
  {key:"away",eyebrow:"Your plans",title:"How long will you be away?",help:"We’ll suggest a starting visit pattern.",options:[["One full day","1"],["A long weekend","3"],["About a week","7"],["Longer than a week","∞"]]},
  {key:"joy",eyebrow:"The important bit",title:"What makes them happiest?",help:"Choose their non-negotiable joy.",options:[["Slow walks & sniffing","〰"],["Cuddles on demand","♡"],["Playtime & zoomies","↗"],["Peace, quiet & routine","○"],["Treat-based negotiations","◇"],["Exploring their habitat","✦"]]}
];

export default function CarePlan(){
  const[screen,setScreen]=useState<"intro"|"quiz"|"loading"|"result">("intro");
  const[step,setStep]=useState(0);const[answers,setAnswers]=useState<Answers>(initial);const[shareStatus,setShareStatus]=useState("Share personality card ↗");
  const q=questions[step];const pet=answers.name.trim()||"Luna";const progress=((step+1)/5)*100;
  const persona=useMemo(()=>answers.personality==="Professional chaos goblin"?"The Lovable Wildcard":answers.personality==="Independent royalty"?"The Tiny Monarch":answers.personality==="Calm little observer"?"The Gentle Watcher":answers.personality==="Friendly with everyone"?"The Social Butterfly":answers.personality==="Shy until snacks appear"?"The Quiet Negotiator":"The Soft-Hearted Explorer",[answers.personality]);
  useEffect(()=>{const p=new URLSearchParams(window.location.search);if(p.get("card")!=="1")return;setAnswers({name:p.get("pet")||"Luna",animal:p.get("animal")||"Pet",personality:p.get("personality")||initial.personality,needs:(p.get("needs")||"").split("|").filter(Boolean),away:p.get("away")||initial.away,joy:p.get("joy")||initial.joy});setScreen("result");setTimeout(()=>document.getElementById("care-plan")?.scrollIntoView(),50)},[]);
  function choose(value:string){if(q.key==="needs")setAnswers(a=>({...a,needs:value==="None right now"?[value]:[...a.needs.filter(x=>x!=="None right now"&&x!==value),value]}));else setAnswers(a=>({...a,[q.key]:value}));}
  function selected(value:string){const v=answers[q.key as keyof Answers];return Array.isArray(v)?v.includes(value):v===value}
  function next(){if(step<4)setStep(step+1);else{setScreen("loading");setTimeout(()=>setScreen("result"),1100)}}
  function restart(){setAnswers(initial);setStep(0);setScreen("intro");history.replaceState({},"",window.location.pathname+"#care-plan")}
  const whatsapp=`https://wa.me/306980770839?text=${encodeURIComponent(`Hi Melissanthi! I created a starter care plan for ${pet}, my ${answers.animal.toLowerCase()}. They are ${answers.personality.toLowerCase()} and love ${answers.joy.toLowerCase()}. We'll be away: ${answers.away.toLowerCase()}. Special notes: ${answers.needs.join(", ")||"none"}. Could we arrange a meet & greet?`)}`;
  async function sharePersonality(){
    const params=new URLSearchParams({card:"1",pet,animal:answers.animal,personality:answers.personality,needs:answers.needs.join("|"),away:answers.away,joy:answers.joy});const url=`${location.origin}${location.pathname}?${params.toString()}#care-plan`;const text=`${pet} is ${persona}. ${answers.personality}. Created with Kypseli Pet Sitting.`;
    const c=document.createElement("canvas");c.width=1080;c.height=1350;const x=c.getContext("2d");if(!x)return;x.fillStyle="#e7b497";x.fillRect(0,0,1080,1350);x.fillStyle="#2b2926";x.font="600 30px Georgia";x.fillText("KY P S E L I   P E T   S I T T I N G",70,90);x.font="600 78px Georgia";x.fillText(`${pet} is`,70,235);x.font="600 100px Georgia";let line="",y=355;for(const w of persona.split(" ")){const t=`${line}${w} `;if(x.measureText(t).width>900&&line){x.fillText(line,70,y);line=`${w} `;y+=112}else line=t}x.fillText(line,70,y);x.font="500 34px Arial";x.fillText(answers.personality,70,y+78);x.font="400 28px Arial";x.fillText(`Happiest with ${answers.joy.toLowerCase()}.`,70,y+128);const img=new Image();img.src=characters[answers.personality];await new Promise<void>(r=>{img.onload=()=>r();img.onerror=()=>r()});if(img.naturalWidth){const ratio=Math.min(700/img.naturalWidth,550/img.naturalHeight);const w=img.naturalWidth*ratio,h=img.naturalHeight*ratio;x.drawImage(img,1080-w-40,1350-h-30,w,h)}x.font="600 24px Arial";x.fillText("kypselipetsitting.gr",70,1280);const blob=await new Promise<Blob|null>(r=>c.toBlob(r,"image/png"));const file=blob?new File([blob],`${pet.toLowerCase().replace(/[^a-z0-9]+/g,"-")}-personality.png`,{type:"image/png"}):null;
    try{if(file&&navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:`${pet}'s care personality`,text,url,files:[file]})}else if(navigator.share)await navigator.share({title:`${pet}'s care personality`,text,url});else{await navigator.clipboard.writeText(url);if(blob){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=file?.name||"pet-personality.png";a.click()}setShareStatus("Link copied + card saved ✓");return}setShareStatus("Shared ✓")}catch(e){if((e as Error).name!=="AbortError"){await navigator.clipboard?.writeText(url);setShareStatus("Link copied ✓")}}setTimeout(()=>setShareStatus("Share personality card ↗"),2500);
  }
  return <section className="care" id="care-plan">
    {screen==="intro"&&<div className="care-intro"><div><p className="care-label">A little help from Meli’s assistant</p><h2>Let’s build your pet’s <em>happy</em> care plan.</h2><p>Five friendly questions create a thoughtful starting point for your meet and greet.</p><label>Pet’s name <small>(optional)</small><input value={answers.name} onChange={e=>setAnswers({...answers,name:e.target.value})} placeholder="e.g. Luna"/></label><button className="care-primary" onClick={()=>setScreen("quiz")}>Create their plan <span>→</span></button><small>Takes about 30 seconds. No medical advice and no data saved.</small></div><div className="care-intro-art"><img src="/pixel-characters/affectionate-dog.svg" alt=""/><p>Personality matters.<br/>Routine comes first.</p></div></div>}
    {screen==="quiz"&&<div className="care-quiz"><aside><button onClick={()=>step?setStep(step-1):setScreen("intro")}>← Back</button><div><p className="care-label">Pet care assistant</p><h2>A better plan starts with the little things.</h2></div><b>{String(step+1).padStart(2,"0")} / 05</b></aside><div className="care-question"><div className="care-progress"><i style={{width:`${progress}%`}}/></div><p className="care-label">{q.eyebrow}</p><h3>{q.title}</h3><p>{q.help}</p><div className={`care-options ${q.key==="personality"?"care-personalities":""}`}>{q.options.map(([label,icon])=><button key={label} className={selected(label)?"selected":""} onClick={()=>choose(label)}><span>{q.key==="personality"?<img src={characters[label]} alt=""/>:icon}</span><strong>{label}</strong><i>{selected(label)?"✓":""}</i></button>)}</div><div className="care-actions"><small>Question {step+1} of 5</small><button className="care-primary" onClick={next}>{step===4?"Build the plan":"Continue"} <span>→</span></button></div></div></div>}
    {screen==="loading"&&<div className="care-loading"><span>✦</span><p className="care-label">Meli’s assistant is thinking</p><h2>Building {pet}’s happiest routine…</h2></div>}
    {screen==="result"&&<div className="care-result"><header><p className="care-label">Your personalized starting point</p><h2>Meet {pet}’s care plan.</h2><p>Melissanthi will confirm every detail with you before booking.</p></header><div className="care-result-grid"><article className="care-plan-card"><small>Recommended care rhythm · {answers.animal} · {answers.away}</small><h3>{answers.away==="One full day"?"Two thoughtful check-ins":"Morning + evening visits"}</h3><p>A calm start, familiar routines and enough time for {answers.joy.toLowerCase()}.</p><div className="care-times"><p><b>09</b><span><strong>Morning hello</strong>Food, fresh water and a relaxed start.</span></p><p><b>18</b><span><strong>Evening reset</strong>{answers.joy}, dinner and a photo update.</span></p></div></article><article className="care-persona-card"><img src={characters[answers.personality]} alt=""/><p className="care-label">{pet}’s care personality</p><h3>{persona}</h3><p>{answers.personality}. Happiest with {answers.joy.toLowerCase()}.</p><button onClick={sharePersonality}>{shareStatus}</button></article><article className="care-notes"><p className="care-label">Care notes</p><h3>The little things we’ll remember</h3><div><p><b>Comfort cue</b>{answers.joy}</p><p><b>Special care</b>{answers.needs.length?answers.needs.join(" · "):"No additional needs selected"}</p><p><b>Your updates</b>Photos and a message after each visit</p></div></article><article className="care-human"><p className="care-label">Human checked, always</p><h3>AI starts the conversation. Melissanthi makes the plan.</h3><p>This is a friendly starting point, not a diagnosis or confirmed booking.</p></article></div><div className="care-cta"><div><small>Ready for the human part?</small><h3>Send this plan to Melissanthi.</h3></div><div><a href={whatsapp} target="_blank" rel="noreferrer">Continue on WhatsApp ↗</a><button onClick={restart}>Start again</button></div></div></div>}
  </section>
}
